### ISSUE TITLE
Browser caching

### ISSUE THREAD

**Issue by wayneashleyberry** [we-are-next/next-website#2]
- Expiration is missing on font and icon files
- Expiration can be increased to a month on all images

<img width="1020" alt="screen shot 2016-11-21 at 3 40 31 pm" src="https://cloud.githubusercontent.com/assets/727262/20484649/e29ebb48-b000-11e6-8a2a-7e2f50c58ad2.png">

<img width="761" alt="screen shot 2016-11-21 at 3 44 40 pm" src="https://cloud.githubusercontent.com/assets/727262/20484763/719565b8-b001-11e6-924f-3b2a1344e6e5.png">

**Comment by Warra** [comment]
Updated the Caddyfile
