### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by wayneashleyberry** [we-are-next/next-website#5]
All of the open graph and twitter meta tags are empty. We should at least have `title`, `description` and `url` in there.

https://github.com/we-are-next/next-website/blob/0d882396b580fad461aa34b36544bb100b74879e/layouts/partials/header.html#L14-L26

**Comment by Warra** [comment]
e66b7790e7e020529fea23cce495c2eb09e0783d
de7f2081d58849183733ab39fd555a375134568d
