### ISSUE TITLE
RIP Logos

### ISSUE THREAD

**Issue by bagf** [we-are-next/next-website#7]
![screen shot 2016-11-22 at 5 01 28 pm](https://cloud.githubusercontent.com/assets/2567601/20528575/74465c2a-b0d5-11e6-9e3b-a05c8c392541.png)
Some README.md refer to the old path http://www.wearenext.co.za/assets/images/logos/logo-next-dark-57x22.png
I can update these paths just need to know what the suitable replacement would be.

**Comment by michaelthorne** [comment]
This is the new logo:

https://wearenext.co.za/images/logos/logo-next-74x28.png
https://wearenext.co.za/images/logos/logo-next-74x28@2x.png
